##	Set directory of all the coverage files	##

setwd("set directory where you save your coverage outputs generated by bedtools")

##	Prepare case and reference list	##
## For example, if you save your coverage output of references under the directory "refs" and cases under the directory "Cases" 

filenames<- dir("refs")[grep(".all.coverage", dir("refs"))]
coverage_all<- list()
for(i in 1: length(filenames))
{
 tmp_data2<- read.delim(paste("refs\\", filenames[i], sep=""), colClasses = c("character", "numeric", "numeric", "NULL", "numeric", "numeric", "numeric", "numeric"), header=F, sep="\t")
 coverage_all[[i]]<- tmp_data2
}

filenames_cases<- dir("Cases")[grep("all.coverage", dir("Cases"))]
coverage_all_cases<- list()
for(i in 1: length(filenames_cases))
{
 tmp_data2<- read.delim(paste("Cases\\", filenames_cases[i], sep=""), colClasses = c("character", "numeric", "numeric", "NULL", "numeric", "numeric", "numeric", "numeric"), header=F, sep="\t")
 coverage_all_cases[[i]]<- tmp_data2
}

## "coverage_all_cases" and "coverage_all" can be used as inputs for "case" and "ref" in function "GB_CNVs_EL"
